# ----------------------------------------------------------------------------
# Description
# ----------------------------------------------------------------------------

# experiment_config.yaml: 
# settings related to the experiment being run when the bandit.py script is 
# launched, it is imported as a Python dictionary object

# for more details about specifying this file, see:
# http://www.isolver-solutions.com/iohubdocs/iohub/api_and_manual/iohub_process/config_files.html

# there is a custom "parameters" section that modifies the behavior of the 
# experimental task and the appearance (colors, element sizes etc)


# ----------------------------------------------------------------------------
# Setting up the configuration
# ----------------------------------------------------------------------------

# ----
# General experiment information
# ----

experiment_id: stationary
title: Values and uncertainty jointly drive the attention dynamics in decision making
code: UncertaintyAttentionRL
version: '1.6'
description: This study examines attention in reinforcement learning tasks, examining the hypothesis that option values and uncertainty about the values jointly drive the attention dynamics.
display_experiment_dialog: True


# ----
# Haoxue Setting
# ----
# Set this variable to True if you use the built-in retina screen as your
# primary display device on macOS. If have an external monitor, set this
# variable True if you choose to "Optimize for Built-in Retina Display"
# in the Displays preference settings.
use_retina: True
# Set this variable to True to run the script in "Dummy Mode"
dummy_mode: True
# Set this variable to True to run the script in "Debug Mode", which is independent from the dummy_mode
debug_mode: True
# Set this variable to True to run the task in full screen mode
# It is easier to debug the script in non-fullscreen mode
full_screen: True
codeVers: 1
cond: [
    ['R', 'S'],
    ['S', 'R'],
    ['R', 'R'],
    ['S', 'S'],
]
labels: ['S', 'R']
starting_coins: 250
scaling_factor: 0.01
n_blocks: 30
n_trials: 10
n_blocks_debug: 2
n_trials_debug: 3

sd_observe: 4
sd_mean_mu: 10
sd_rw: 0

start_coin: 250

monitor:
    width: 53.0
    distance: 70.0
    
calibration:
# Set background and foreground colors for the calibration target
# in PsychoPy, (-1, -1, -1)=black, (1, 1, 1)=white, (0, 0, 0)=mid-gray
    foreground_color: [1,1,1]
    background_color: [0, 0, 0] # originally they used win.color, not sure whether i could do this in .yaml file
msg:
    msgColor: [1,1,1]
type:
    typeColor: [1,1,1]
    typeSize: 50
    typeBold: True
fixation:
    fixColor: [1,1,1]
    fixLineWidth: 5
    fixSize: 25
rect:
    rectWidth: 400
    rectHeight: 400
    rectLineWidth: 7
    rectDistCenter: 100
    rectColor: [1,1,1]  
keys:
    left_key: 'q'
    right_key: 'p'
trial:
    fixation_length_min: 1.0
    fixation_length_max: 2.0
    stimulus_pre_with_fixation_length: 3.0
    stimulus_pre_without_fixation_length_max: 1.5
    reward_pre_without_fixation_length: 3.0
    extra_fixation_length: 2.0
    fixation_length_min_debug: 1.0
    fixation_length_max_debug: 1.5
    stimulus_pre_with_fixation_length_debug: 1.5
    stimulus_pre_without_fixation_length_max_debug: 1.0
    reward_pre_without_fixation_length_debug: 1.5
    extra_fixation_length_debug: 0.5
baseline_length: 300
baseline_length_debug: 10    
    

